# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ReFLEX Lab Wiki
email: contact@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Documentation for computing resources, hardware, and lab procedures.
  A comprehensive guide for lab members.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
theme: just-the-docs
plugins:
  - jekyll-feed

# Just the Docs theme settings
# Enable search functionality
search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/
  rel_url: true
  button: false

# Auxiliary navigation for the top right
aux_links:
  "GitHub":
    - "https://github.com/ReFLEX-Lab-York"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
footer_content: "Copyright &copy; 2025 ReFLEX Lab. Distributed by an <a href=\"https://github.com\">MIT license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Color scheme options: light, dark, or custom
# Use 'custom' to apply the custom.scss color scheme with enhanced syntax highlighting
color_scheme: custom

# Enable heading anchors
heading_anchors: true

# Table of Contents (TOC) configuration
# By default, TOC is disabled. Enable it per page with "toc: true" in front matter
# Or uncomment below to enable globally (not recommended for all pages)
# Note: TOC will show H2 and H3 headings by default

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
